spring.main.banner-mode: off

spring.datasource:
  url: jdbc:postgresql://localhost:5432/test
  username: test
  password: test

notifier:
  sendgrid:
    apiKey: ${SENDGRID_API_KEY}
    fromEmail: notifier@example.com
    templateId: d-273a693ea06544b6a7894bed512f9af6
    sandboxMode: true
  reddit.url: 'https://www.reddit.com'
